baseURL = 'https://tl2-mod.chr.moe'
languageCode = 'zh-CN'
title = 'Torchlight 2'
theme = 'paper'
googleAnalytics = 'G-WSK4F982KY'


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'heiybb'                 # github.com/YOUR_GITHUB_ID

  rss = true                                # show rss icon

  # home page profile
  #avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  #name = 'YOUR_NAME'
  #bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = false                               # enable KaTex math typesetting globally